autograd를 알아보자

In [2]:
import torch
from torch.autograd import Variable

x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
z = y ** 2 * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [5]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


실제로 해볼까?

sum을 알아보자.

In [12]:
a = torch.randn(4, 4, 4)
print(a)

tensor([[[-1.4149, -0.7851, -0.6575, -1.7467],
         [-0.5330, -1.3436, -2.6032, -1.1334],
         [ 0.6661,  1.1374,  0.5445,  0.6232],
         [-0.4807, -0.8843, -0.7020, -0.4060]],

        [[-0.3075,  1.0332,  0.1442, -0.3699],
         [ 0.4513,  2.1771, -1.0212, -0.4164],
         [-0.7743,  1.5907,  0.2185, -0.5893],
         [-0.8135,  0.6542,  0.2552,  1.0941]],

        [[-1.3460,  1.6761,  0.1953, -2.0411],
         [-0.9927, -1.0136, -0.5453,  0.5582],
         [ 0.0067, -1.8157, -2.1219, -1.1818],
         [-0.9966,  1.6804,  0.5346,  0.4292]],

        [[-0.9246,  0.3626,  0.0710,  1.1230],
         [-2.7487,  0.3232, -0.3732, -1.1262],
         [ 0.6088, -1.6641, -0.7012,  0.4911],
         [-0.2628, -0.1010,  1.0371,  0.9469]]])


In [24]:
torch.sum(a)

tensor(-16.3050)

dim은 axis이다.

In [28]:
torch.sum(a, 0)

tensor([[-3.9930,  2.2868, -0.2470, -3.0348],
        [-3.8232,  0.1431, -4.5429, -2.1177],
        [ 0.5074, -0.7517, -2.0601, -0.6568],
        [-2.5536,  1.3493,  1.1249,  2.0642]])

In [25]:
torch.sum(a, 1)

tensor([[-1.7624, -1.8756, -3.4182, -2.6629],
        [-1.4440,  5.4553, -0.4033, -0.2815],
        [-3.3286,  0.5272, -1.9374, -2.2355],
        [-3.3273, -1.0793,  0.0338,  1.4347]])

In [26]:
torch.sum(a, 2)

tensor([[-4.6042, -5.6132,  2.9712, -2.4729],
        [ 0.5000,  1.1909,  0.4456,  1.1900],
        [-1.5158, -1.9934, -5.1127,  1.6477],
        [ 0.6320, -3.9250, -1.2653,  1.6201]])

조금 더 확실히 보자.

In [31]:
torch.sum(a, 0, keepdim=True)

tensor([[[-3.9930,  2.2868, -0.2470, -3.0348],
         [-3.8232,  0.1431, -4.5429, -2.1177],
         [ 0.5074, -0.7517, -2.0601, -0.6568],
         [-2.5536,  1.3493,  1.1249,  2.0642]]])

In [32]:
torch.sum(a, 1, keepdim=True)

tensor([[[-1.7624, -1.8756, -3.4182, -2.6629]],

        [[-1.4440,  5.4553, -0.4033, -0.2815]],

        [[-3.3286,  0.5272, -1.9374, -2.2355]],

        [[-3.3273, -1.0793,  0.0338,  1.4347]]])

In [33]:
torch.sum(a, 2, keepdim=True)

tensor([[[-4.6042],
         [-5.6132],
         [ 2.9712],
         [-2.4729]],

        [[ 0.5000],
         [ 1.1909],
         [ 0.4456],
         [ 1.1900]],

        [[-1.5158],
         [-1.9934],
         [-5.1127],
         [ 1.6477]],

        [[ 0.6320],
         [-3.9250],
         [-1.2653],
         [ 1.6201]]])

view의 활용

In [5]:
x = torch.randn(4, 4)
print(x)

tensor([[ 1.4413, -0.6682,  2.1738,  1.8203],
        [ 1.2624, -0.5270, -0.2141,  0.7535],
        [-0.5452,  0.3324,  0.0871, -0.3054],
        [ 1.7908, -0.9432,  0.8418, -0.5915]])


In [38]:
y = x.view(-1, 2)
print(y)

tensor([[ 1.5808, -1.8178],
        [-0.2032, -0.4119],
        [-0.1843,  0.5460],
        [ 1.2609, -0.4491],
        [ 0.9133, -0.3498],
        [-0.1893, -0.7692],
        [ 1.0524,  1.2463],
        [-0.0778,  0.0379]])


In [6]:
z = x.view(-1, 16)
print(z)

tensor([[ 1.4413, -0.6682,  2.1738,  1.8203,  1.2624, -0.5270, -0.2141,  0.7535,
         -0.5452,  0.3324,  0.0871, -0.3054,  1.7908, -0.9432,  0.8418, -0.5915]])
